### ISSUE TITLE
Alguém sabe como se formam os números romanos?

### ISSUE THREAD

**Issue by Judahh** [pisandelli/trainee2015#13]
Alguém sabe como se formam os números romanos? Pq todos os sites que pesquisei eles só dão algumas regras que acabam permitindo ambiguidade e as vezes  algumas delas estão erradas, sem contar que nenhum fala como se formam (que eu achei). A solução que propus resolve todos os testes que fiz (que foram um bocado), mas não garanto nada pq eu não tenho certeza de como realmente se forma o número romano, embora eu criei uma teoria vendo alguns números feitos na internet.

**Comment by pisandelli** [comment]
@Judahh Estou usando essas regras para criar o script `Python`
http://www.somatematica.com.br/romanos.php
