### ISSUE TITLE
Código Java e código python

### ISSUE THREAD

**Issue by Daniel-Aragao** [pisandelli/trainee2015#14]
bom, fiz um código que não me achei no direito de substituir o código coletivo, mas gostaria de comentários a respeito do mesmo, também fiz um em python meio que numa rápida conversão manual e adoraria receber dicas de como melhora-lo já que comecei a estuda-lo recentemente

Não postarei os testes para não ficar muito poluído, mas no final estavam todos verdes

**Comment by Daniel-Aragao** [comment]
Problema: Algarismos Romanos
Java:

import java.util.Map;
import java.util.HashMap;

public class Conversor {

	Map<Character, Integer> algarismos = new HashMap<Character, Integer>();

	public Conversor() {
		algarismos.put('X', 10);
		algarismos.put('V', 5);
		algarismos.put('I', 1);
		algarismos.put('C', 100);
		algarismos.put('L', 50);
		algarismos.put('D', 500);
		algarismos.put('M', 1000);
	}

	public int conversão(String romano) throws Exception {
		if (romano == "") {
			throw new Exception("Algarismo inválido");
		}
		
		int result = 0;
		char anterior = 0, antanterior = 0;

		if (repetição(romano)) {
			throw new Exception("Algarismos que se repetem indevidamente");
		}
		
		for (Character letra : romano.toCharArray()) {

			Integer a = algarismos.getOrDefault(letra, 0);
			Integer b = algarismos.getOrDefault(anterior, 0);
			result += algarismos.get(letra);

			if (a == 0) {
				throw new Exception("Algarismo não romano presente");
			}

			if (b < a) {
				result -= 2 * algarismos.getOrDefault(anterior, 0);

			}

			if (algarismos.getOrDefault(antanterior, 0) < a && antanterior != 0) {
				throw new Exception("Algarismos incoerente");
			}

			antanterior = anterior;
			anterior = letra;
		}

		return result;
	}

	private boolean repetição(String algarismo) {

		for (int cont = 1, i = 0; i < algarismo.length() - 1; i++) {

			if (algarismo.charAt(i) == algarismo.charAt(i + 1)) {
				if (algarismo.charAt(i) == 'V' || algarismo.charAt(i) == 'L'
						|| algarismo.charAt(i) == 'D') {
					return true;
				}

				cont++;
				if (cont > 3) {
					return true;
				}
			} else {
				cont = 1;
			}
		}

		return false;
	}

}

**Comment by Daniel-Aragao** [comment]
Problema: Algorismo Romano
Python

class Conversor(object):

	def __init__ (self):
		self.algarismos = {'X': 10,'V': 5,'I': 1,'C': 100,'L': 50,'D': 500,'M': 1000}
	
		
	

	def convercao ( self,romano) :
		
		if (romano == ""):
			raise NameError("Algarismo inválido")
		
		
		result = 0
		anterior = 0
		antanterior = 0

		if (self.repeticao(romano)):
			raise NameError("Algarismos que se repetem indevidamente")
		
		
		for  letra in romano:

			a = self.algarismos.get(letra, '0')
			b = self.algarismos.get(anterior, 0)

			result += a

			if (a == '0'):
				raise NameError("Algarismo nao romano presente")
			

			if (b < a):
				result -= 2 * self.algarismos.get(anterior, 0)

			

			if (self.algarismos.get(antanterior, 0) < a and antanterior != 0):
				raise NameError("Algarismos incoerente")
			

			antanterior = anterior
			anterior = letra
		

		return result
	

	def repeticao(self, algarismo):
		cont = 1

		for i in range( algarismo.__len__()-1):

			if (algarismo[i] == algarismo[i+ 1]):
				if (algarismo[i] == 'V' or algarismo[i] == 'L'
						or algarismo[i] == 'D'):
					return True
				
				cont+=1
				if (cont > 3):
					return True
			else:
				cont = 1
			
		return False

**Comment by Judahh** [comment]
Eu tb quando fiz o meu não quis substituir o coletivo, por isso no meu pull request eu fiz um arquivo novo.

**Comment by Daniel-Aragao** [comment]
pensei em faze-lo, porém a pasta está meio aberta e para evitar confusão ou desorganização sabe? preferi deixar como estava.

**Comment by pisandelli** [comment]
Criem uma pasta com o nome de vocês e façam um PR, assim não substitui o
código de ninguém! :)

Em 31 de julho de 2015 10:49, Daniel Aragão <notifications@github.com>
escreveu:
