### ISSUE TITLE
Otimizar solução JAVA

### ISSUE THREAD

**Issue by pisandelli** [pisandelli/trainee2015#2]
Acredito que a solução em JAVA possa ser otimizada.

**Comment by pisandelli** [comment]
@babiperina, @daniel-aragao, alguém se habilita?

**Comment by babiperina** [comment]
Sim!

**Comment by thiagomcoffice** [comment]
Fiz esse exemplo:

public class BuracosPalavra {

	public int qtdeBuracos(String frase) {
		
		int cont = 0;
		char[] arrayLetras1Buraco = {'A', 'C', 'D', 'O', 'P', 'Q', 'R'};
		
		for(int i = 0; i < frase.length(); i++){
			for(int j = 0; j < arrayLetras1Buraco.length; j++){
				if(arrayLetras1Buraco[j] == frase.charAt(i)){
					cont ++;
				}
			}
			if(frase.charAt(i) =='B'){
				System.out.println("ok");
				cont += 2;
			}
		}
		return cont;
	}

}

**Comment by Daniel-Aragao** [comment]
sim, estou editando, porém com problemas no pc, jaja dou uma PR

**Comment by RicsonSampaio** [comment]
package Solution;

public class ContadorDeBuracosDasPalavras {

	public int contaBuracos(String palavra) {
		int cont = 0;
		for (int i = 0; i < palavra.length(); i++) {
			char letra = palavra.charAt(i);
			
			switch (letra){
				case 'A':
				cont++;
				break;
				
				case 'B':
				cont = cont + 2;
				break;
				
				case 'D':
				cont++;
				break;
				
				case 'O':
				cont++;
				break;
				
				case 'P':
				cont++;
				break;
				
				case 'Q':
				cont++;
				break;
				
				case 'R':
				cont++;
				break;

			}
					
		}
	return cont;
	}

}

**Comment by RicsonSampaio** [comment]
package TestsUnit;

import static org.junit.Assert.*;

import org.junit.Test;

import Solution.ContadorDeBuracosDasPalavras;

public class Digitando_A_Palavra {

	@Test
	public void verificando_Se_A_Tem_1_Buraco() {
		
		//Arrange
		ContadorDeBuracosDasPalavras contador = new ContadorDeBuracosDasPalavras();
		
		//Act
		
		int numeroDeBuracos = contador.contaBuracos("A");
		
		//Assert
		
		assertEquals(1, numeroDeBuracos);
	}

	@Test
	public void verificando_Se_B_Tem_2_Buracos() {
		
		//Arrange
		ContadorDeBuracosDasPalavras contador = new ContadorDeBuracosDasPalavras();
		
		//Act
		
		int numeroDeBuracos = contador.contaBuracos("B");
		
		//Assert
		
		assertEquals(2, numeroDeBuracos);
	}
	
	@Test
	public void verificando_Quantos_Buracos_A_Palavra_Tem() {
		
		//Arrange
		ContadorDeBuracosDasPalavras contador = new ContadorDeBuracosDasPalavras();
		
		//Act
		
		int numeroDeBuracos = contador.contaBuracos("PNEUMOULTRAMICROSCOPICOSSILICOVULCANOCONIOTICO");
		
		//Assert
		
		assertEquals(15, numeroDeBuracos);
	}
}

**Comment by pisandelli** [comment]
@thiagomcoffice, sua solução é bem interessante, mas que tal dar uma olhada na versão [Python](https://github.com/pisandelli/trainee2015/blob/master/dojo_buraco_letras/python/dojo.py) ou [JS](https://github.com/pisandelli/trainee2015/blob/master/dojo_buraco_letras/js/dojo.js) para dar uma inspirada, hein?
Por exemplo, porque não usar um Dicionário (existe isso em JAVA??) como feito no JS e no Python? Talvez seja melhor do que um `for ...` dentro de um `for ...` mesmo caso pro `switch`... não?

@RicsonSampaio, isso é C#?

De qualquer forma, façam o código e façam um Pull Request, adicionando a pasta com o nome da linguagem e dentro o código fonte... :smiley:

**Comment by RicsonSampaio** [comment]
É em Java mesmo hehe. Tudo bem, vou dá uma olhada em uma maneira menos repetitiva e mais organizada. Se achar uma maneira assim, darei um Pull Request ;)

**Comment by pisandelli** [comment]
:+1:
